default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bitter_cherry_CRUD_development
test:
  <<: *default
  database: bitter_cherry_CRUD_test
production:
  <<: *default
  database: bitter_cherry_CRUD_production
  username: bitter_cherry_CRUD
  password: <%= ENV['BITTER_CHERRY_CRUD_DATABASE_PASSWORD'] %>
